name: Q1

on: [push]
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Création du fichier Q1_archive_README.md
        run: cat README.md > Q1_archive_README.md

      # Runs a set of commands using the runners shell
      - name: XXX commmit et push
        run: |
          git config --global user.name AllanLegrand
          git config --global user.email allan.legrand16@gmail.com
          git add Q1_archive_README.md
          git commit -m "Création de Q1_archive_README.md, clone de README.md"
          git push
