name: Q1

on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Création du fichier Q1_archive_README.md
        run: cat README.md > Q1_archive_README.md

      - name: XXX commmit et push
        run: |
          git config --global user.name AllanLegrand
          git config --global user.email allan.legrand16@gmail.com
          git add Q1_archive_README.md
          git commit -m "Création de Q1_archive_README.md, clone de README.md"
          git push
