name: Q5

on: [push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Créer le fichier Q5_archive_java.txt avec mon prénom et mon nom
        run: echo "# Allan LEGRAND" > "Q5_"$(timedatectl | head -n 1 | cut -d '-' -f 3 | cut -d ' ' -f 1)"-"$(timedatectl | head -n 1 | cut -d '-' -f 2)"-"$(timedatectl | head -n 1 | cut -d '-' -f 1 | cut -d ' ' -f 19)".txt"
        
      - name: Recopier Q4.java en Q5.java
        run: |
          echo "public class Q5 {" > Q5.java
          cat Q4.java | grep -v "public class Q4" >> Q5.java
          

      
      - name: XXX commmit et push
        run: |
          git config --global user.name AllanLegrand
          git config --global user.email allan.legrand16@gmail.com
          git add Q5*
          git commit -m "Création de Q5_archive_date.txt et Q5.java"
          git push
